spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mpg?serverTimezone=UTC&characterEncoding=UTF-8
    username: matpago
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.example.react
  mapper-locations: mybatis/mapper/**/*.xml